application: uits-eas
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.*-hipmail@uits-eas.appspotmail.com
  script: hipmailer.py 

- url: .*
  script: main.py
  
inbound_services:
- mail
